sudo: required
language: java
install: true
script: "./gradlew assemble"
before_install:
- chmod +x gradlew
deploy:
  provider: releases
  api_key:
    secure: TzRdB0QOCVKz+WHQmIsYGlgnT0Y5C6Mn4WjM6JBiKO4lQG5vYXoHhxturtoOFoM0dROaPrMwqgZk9bNS5icZoP+hQJGIsUtFlvyi7WOjf4PROu+HJNoGHYAtAELLGudfQ9G9R6RQCFdagANSH7qmo4l8KaABFnhaCA/EV6u72oZRRnobTh64DWcq61s3HTSY3C09tIenLPbkos+trtg1khFpvBro9e+hGtjOZvAYhMZdeXu5ddt0QawWSiWdeLIv2iQTpqhisyD2n8CJng03jlSY40D5pFU3Nl/Jj6Ywppk9JKLTTEb4M2zh20NsPsw1APOx1SzG3KnS8+Gp0W5ExH078LjsB2OsOYQnHEG/VLPI07KUe+lfcZl1WSlU/udHWbRQicR3gb/ZIqeHI6BDA6FsNg8y2NG6redL50OyNMqPZ2juvvtiZNFVgpWX51fQeIzvMGBXkdDCLy06KP+SbC4NiKzrFWXnbTHBOLBAqZNveHAN5X1Rg29b6VDxhd/vMnStli5P+jwu17IFwJlsdUWPnyDz/FqIxsr36DJgGn3dHquQ+YA0EZWatRKYJ35yzrRtN8/Yz3mpxuAjusUtjXiJ5AERHuGwRarMH+iSVH9YaeOBODGm/zHLG/zdKX8RLqo1MOR/1fDgxcZFfkPn0PTpEaUjH7FfxtwwRTEvYM0=
  file: "./build/distributions/xld-conjur-plugin-1.0.0.xldp"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-conjur-plugin
notifications:
  slack:
    secure: eRKOiNLllMswq1ks16d9hNp+Ui+9WvWtkQ0fU0N62hUqM3nxi0/jE5M6gowLsOnQZSgGkzXfn6zWAhYLynD/Vp97nw8XMCdq0IfnlS3a6eLtU7xdXQgec43P2+8AQWRducqDhUR4KjZLaHFbsrymQ+xT+m7Tv3bjik3ddL7NPq6nIDjLwb2ibyyucMmcKqDNzKqKnaevDzj9Z3czHGoHe1ZDP/TDGZFOZ65JkFA1rEEDwvwADPKqQY1rGQHBecYP70Q6oKJnNY9TGYMUiF/7wWiJO0KTe6yrQ9ksIOL4IyPXcS4bA4i34fwpy+Gi9pPoeMt1LHtHdRIR67NTlCnYkOdz5PlQZQWxyEIlgUC7xjuGo/YSkj/dkwMQ7y5fQ+HT8mU5c7jgA+EKzD+1oGehQESbTMxtN3ybsg5N02ElPhEjn+cg9phEFMiGF2HwnNw9JrHUGGqjZFG+BU4dN+RSpNuLSjrUl2vouUZWUO5ojEKLBKzjViA33lrztXPXmqaKq/shYVxsoRKpXP0J0vePE7fqu/DQmoZip+aR7g5NXAKwRmJ/2n8MQG3exZJDNha3eB6amF8KF+Snzyy/rCrjgI4hJgs838M+88WO3Zw977fE654pU/1NXozdecHgi9Wc8xVCKUVUUaEPrABkwLLvRsgv1pt81k6g+useEM0sHQY=
